SET VERIFY OFF

DEFINE dev_password = '&1'
DEFINE test_password = '&2'

ALTER SESSION SET CONTAINER = XEPDB1;

DECLARE
  user_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_exists FROM dba_users WHERE username = 'SLOW_DATING_DEV';
  IF user_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER SLOW_DATING_DEV IDENTIFIED BY "&&dev_password"';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER SLOW_DATING_DEV IDENTIFIED BY "&&dev_password"';
  END IF;
END;
/

DECLARE
  user_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_exists FROM dba_users WHERE username = 'SLOW_DATING_TEST';
  IF user_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER SLOW_DATING_TEST IDENTIFIED BY "&&test_password"';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER SLOW_DATING_TEST IDENTIFIED BY "&&test_password"';
  END IF;
END;
/

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO SLOW_DATING_DEV;
ALTER USER SLOW_DATING_DEV QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO SLOW_DATING_TEST;
ALTER USER SLOW_DATING_TEST QUOTA UNLIMITED ON USERS;

EXIT SUCCESS
