CREATE TABLE schema_migrations (
  version VARCHAR2(100) PRIMARY KEY,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL
)
-- statement
CREATE TABLE app_users (
  id VARCHAR2(36) PRIMARY KEY,
  phone_e164 VARCHAR2(20) NOT NULL UNIQUE,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  identity_status VARCHAR2(20) DEFAULT 'NOT_STARTED' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT ck_user_status CHECK (status IN ('ACTIVE','SUSPENDED','DELETED')),
  CONSTRAINT ck_identity_status CHECK (identity_status IN ('NOT_STARTED','PENDING','VERIFIED','REJECTED'))
)
-- statement
CREATE TABLE otp_challenges (
  id VARCHAR2(36) PRIMARY KEY,
  phone_e164 VARCHAR2(20) NOT NULL,
  code_digest VARCHAR2(64) NOT NULL,
  attempts NUMBER(2) DEFAULT 0 NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  consumed_at TIMESTAMP WITH TIME ZONE NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL
)
-- statement
CREATE INDEX ix_otp_phone_created ON otp_challenges(phone_e164, created_at)
-- statement
CREATE TABLE refresh_sessions (
  id VARCHAR2(36) PRIMARY KEY,
  user_id VARCHAR2(36) NOT NULL REFERENCES app_users(id),
  token_digest VARCHAR2(64) NOT NULL UNIQUE,
  device_name VARCHAR2(120) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  revoked_at TIMESTAMP WITH TIME ZONE NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL
)
